FROM python:3.6

EXPOSE 5000
WORKDIR /code
ADD requirements.txt /code/

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ADD . /code/

CMD ["sh", "-c", "flask db upgrade heads && gunicorn -c etc/gunicorn.conf.py main:app"]



