"""add_relationship_of_creating_room

Revision ID: 966ed193a148
Revises: 663de9f26aad
Create Date: 2020-04-14 02:03:25.746157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '966ed193a148'
down_revision = '663de9f26aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'room_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('reactions', 'message_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('reactions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('rooms', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'users', ['creator_id'], ['id'])
    op.alter_column('songs', 'room_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'song_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'song_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'room_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'creator_id')
    op.alter_column('reactions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('reactions', 'message_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'room_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
