"""add_user

Revision ID: f0093ff08f0c
Revises:
Create Date: 2019-03-13 07:01:52.909735

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0093ff08f0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('email', sa.String(length=191), nullable=False),
                    sa.Column('username', sa.String(length=191),
                              nullable=False),
                    sa.Column('fullname', sa.String(length=191),
                              nullable=False),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.Column('password_hash', sa.String(length=100),
                              nullable=True),
                    sa.Column('id_token', sa.String(length=512), nullable=True),
                    sa.Column('image', sa.Text(), nullable=True),
                    sa.Column('role', sa.Enum('admin', 'moderator', 'viewer',
                                              name='role'), nullable=False),
                    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
